version: '3.8'

services:
  app:
    container_name: app
    build: .
    entrypoint: sh -c 'dockerize -wait tcp://db:3306 -timeout 20s yarn prisma migrate deploy && yarn dev'
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - db
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 8080:80
    networks:
      - app-network
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network
    volumes:
      - dbdata:/data/db

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules: